-- ============================================================
-- Seed: KIGH Family Fun Day (upcoming)
-- Idempotent on events.slug.
-- April 24 session materials + single public event live in 006
-- (kigh-financial-literacy-session-2026-04-24); no separate tax
-- calendar row here — avoids duplicate Apr 24 events.
-- ============================================================

INSERT INTO events (
  slug,
  title,
  category,
  description,
  short_description,
  start_date,
  end_date,
  start_time,
  end_time,
  timezone,
  location,
  address,
  city,
  state,
  is_virtual,
  is_free,
  status,
  published_at,
  is_featured,
  image_url,
  flyer_url,
  organizer_name,
  organizer_email
) VALUES (
  'kigh-family-fun-day-2026',
  'KIGH Family Fun Day',
  'Community',
  $fd$KIGH Family Fun Day is still on. Join Kenyans in Greater Houston for a family-friendly community celebration at Cullen Park, Pavilions A1 and A2. Everything is planned as scheduled, including live DJs DJ Ericko and DJ Sasabasi, food and merchandise vendors, bounce houses, face painting, and games for all ages. Bring your children, family, and friends for good vibes, great company, and unforgettable memories. Karibuni nyote.$fd$,
  'A family-friendly KIGH community celebration with live DJs, vendors, bounce houses, face painting, games, food, merchandise, and activities for all ages.',
  '2026-05-02',
  '2026-05-02',
  '12:00:00',
  '19:00:00',
  'America/Chicago',
  'Cullen Park, Pavilions A1 & A2',
  'Houston, TX 77084',
  'Houston',
  'TX',
  false,
  true,
  'published',
  now(),
  true,
  '/kigh-media/events/kigh-family-fun-day-2026.jpeg',
  '/kigh-media/events/kigh-family-fun-day-2026.jpeg',
  'Kenyans in Greater Houston / KIGH',
  null
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date,
  start_time = EXCLUDED.start_time,
  end_time = EXCLUDED.end_time,
  timezone = EXCLUDED.timezone,
  location = EXCLUDED.location,
  address = EXCLUDED.address,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  is_virtual = EXCLUDED.is_virtual,
  is_free = EXCLUDED.is_free,
  status = EXCLUDED.status,
  published_at = EXCLUDED.published_at,
  is_featured = EXCLUDED.is_featured,
  image_url = EXCLUDED.image_url,
  flyer_url = EXCLUDED.flyer_url,
  organizer_name = EXCLUDED.organizer_name,
  organizer_email = EXCLUDED.organizer_email,
  updated_at = now();
